name: CI

on:
  # GitHub has started calling new repo's first branch "main" https://github.com/github/renaming
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

concurrency:
  # Specific group naming so CI is only cancelled
  # within same PR or on merge to main
  group: ${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on {{ '${{ matrix.os }}' }}, Python {{ '${{ matrix.python-version }}' }}
    runs-on: {{ '${{ matrix.os }}' }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      # More info on options: https://github.com/marketplace/actions/provision-with-micromamba
      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: requirements.yaml
          environment-name: mbuild_polybuild
          channels: conda-forge,defaults
          extra-specs: |
            python={{ '${{ matrix.python-version }}' }}
          create-args: >-
            pytest
            pytest-cov
            codecov
      - name: Install package
        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          micromamba list
      - name: Run tests
        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          pytest -v --cov=mbuild_polybuild --cov-report=xml --color=yes mbuild_polybuild/tests/

      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-{{ '${{ matrix.os }}' }}-py{{ '${{ matrix.python-version }}' }}

      - name: docs
        uses: usnistgov/Docs4NIST@0.6
        with:
          docs-folder: docs/
          formats: |-
            epub
            pdf
